# A3.7 Heads to Tails
# REDACTED(I <3 not doxxing myself)
# Take a string from the user and confirm that all characters are either T(tails) or H(heads)
# then find the rightmost H in the string, remove it and change it's immediate neighbours will be flipped from
# heads to tails or tails to heads. This continues until there are no H's left, or a single H.
# if there is a single H left, success! otherwise, fail!

def FlipChar(char):
    if char == 'T':
        return 'H'
    if char == 'H':
        return 'T'
while True:
    try:
        inputStr = input("Please enter a string containing only H/T(heads/tails):")
    except:
        print("This is not a valid string.")
    else:
        invalidCharFound = False
        inputStr = inputStr.upper()
        for i in inputStr:
            if i != 'T' and i != 'H':
                invalidCharFound = True
        if not invalidCharFound:
            break

inputStrList = list(inputStr)
while True:
    hFound = False
    rightHIndex = -1
    for i in range(0,len(inputStrList)):
        if inputStrList[i] == 'H' and i > rightHIndex:
            rightHIndex = i
            hFound = True
    if not hFound:
        print("Not success.")
        break
    else:
        if len(inputStrList) == 1:
            print("Success!")
            break
        else:
            if rightHIndex - 1 >= 0:
                inputStrList[rightHIndex - 1] = FlipChar(inputStrList[rightHIndex - 1])
            if rightHIndex + 1 != len(inputStrList):
                inputStrList[rightHIndex + 1] = FlipChar(inputStrList[rightHIndex + 1])
            inputStrList = inputStrList[:rightHIndex] + inputStrList[rightHIndex + 1:]
            print(*inputStrList, sep="")

# Test cases
"""
Please enter a string containing only H/T(heads/tails):testing123
Please enter a string containing only H/T(heads/tails):HTTHT
HTHH
HTT
HT
H
Success!
"""
"""
Please enter a string containing only H/T(heads/tails):httht
HTHH
HTT
HT
H
Success!
"""
"""
Please enter a string containing only H/T(heads/tails):HHTT
THT
HH
T
Not success.
"""
"""
Please enter a string containing only H/T(heads/tails):HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHHHTTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHT
HHHTTHTHHHTHTTTTTTTTTTTHH
HHHTTHTHHHTHTTTTTTTTTTTT
HHHTTHTHHHHHTTTTTTTTTTT
HHHTTHTHHHTHTTTTTTTTTT
HHHTTHTHHHHHTTTTTTTTT
HHHTTHTHHHTHTTTTTTTT
HHHTTHTHHHHHTTTTTTT
HHHTTHTHHHTHTTTTTT
HHHTTHTHHHHHTTTTT
HHHTTHTHHHTHTTTT
HHHTTHTHHHHHTTT
HHHTTHTHHHTHTT
HHHTTHTHHHHHT
HHHTTHTHHHTH
HHHTTHTHHHH
HHHTTHTHHT
HHHTTHTTH
HHHTTHTH
HHHTTHH
HHHTTT
HTHTT
HHHT
HTH
HH
T
Not success.
"""
"""
Please enter a string containing only H/T(heads/tails):hhhtththhhthtttttttttttthhttttththttttthhthhhhhhthhhhthhththhthththttththhththt
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHHHTTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHTHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTHH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTHTT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTHHT
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTTH
HHHTTHTHHHTHTTTTTTTTTTTTHHTH
HHHTTHTHHHTHTTTTTTTTTTTTHHH
HHHTTHTHHHTHTTTTTTTTTTTTHT
HHHTTHTHHHTHTTTTTTTTTTTHH
HHHTTHTHHHTHTTTTTTTTTTTT
HHHTTHTHHHHHTTTTTTTTTTT
HHHTTHTHHHTHTTTTTTTTTT
HHHTTHTHHHHHTTTTTTTTT
HHHTTHTHHHTHTTTTTTTT
HHHTTHTHHHHHTTTTTTT
HHHTTHTHHHTHTTTTTT
HHHTTHTHHHHHTTTTT
HHHTTHTHHHTHTTTT
HHHTTHTHHHHHTTT
HHHTTHTHHHTHTT
HHHTTHTHHHHHT
HHHTTHTHHHTH
HHHTTHTHHHH
HHHTTHTHHT
HHHTTHTTH
HHHTTHTH
HHHTTHH
HHHTTT
HTHTT
HHHT
HTH
HH
T
Not success.
"""
"""
Please enter a string containing only H/T(heads/tails):HTTHHTH
HTTHHH
HTTHT
HTHH
HTT
HT
H
Success!
"""
"""
Please enter a string containing only H/T(heads/tails):TT
Not success.
"""
"""
Please enter a string containing only H/T(heads/tails):HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHTHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHTHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTTTT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHHHTTT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTHTT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTHTT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHTHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHTHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHHTT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHTHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHTHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHHH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTHHT
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTTH
HHHHTTHTHHHTHHHHHTHHHHTHTHTH
HHHHTTHTHHHTHHHHHTHHHHTHTHH
HHHHTTHTHHHTHHHHHTHHHHTHTT
HHHHTTHTHHHTHHHHHTHHHHHHT
HHHHTTHTHHHTHHHHHTHHHHTH
HHHHTTHTHHHTHHHHHTHHHHH
HHHHTTHTHHHTHHHHHTHHHT
HHHHTTHTHHHTHHHHHTHTH
HHHHTTHTHHHTHHHHHTHH
HHHHTTHTHHHTHHHHHTT
HHHHTTHTHHHTHHHTHT
HHHHTTHTHHHTHHHHH
HHHHTTHTHHHTHHHT
HHHHTTHTHHHTHTH
HHHHTTHTHHHTHH
HHHHTTHTHHHTT
HHHHTTHTHTHT
HHHHTTHTHHH
HHHHTTHTHT
HHHHTTHHH
HHHHTTHT
HHHHTHH
HHHHTT
HHTHT
HHHH
HHT
TH
H
Success!
"""
"""
Please enter a string containing only H/T(heads/tails):HTTHT
HTHH
HTT
HT
H
Success!
"""
"""
Please enter a string containing only H/T(heads/tails):TTTTTTTTTTTTTTTTTTTTT
Not success.
"""
"""
Please enter a string containing only H/T(heads/tails):H
Success!
"""
"""
Please enter a string containing only H/T(heads/tails):T
Not success.
"""